version: '3.8'

services:
  web:
    image: messaging-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/messaging_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
